### PR TITLE
Run init only once, won't redirect through /home

### PR DESCRIPTION
**Pull request by krl**

### CODE REVIEW

**Comment by RichardLitt** [comment]
How do I get it to redirect to init? It doesn't at the moment. Tried restarted the server and the daemon, always just went to home.

**Comment by krl** [comment]
You need to point your ipns somewhere else to reset, the empty directory for example:

```
ipfs name publish QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn
```

**Comment by RichardLitt** [comment]
Ok. How do I do that? Right now, I have two terminals running: 

``` sh
$ ipfs daemon
# And..
$ npm run serve
```

Should I cancel one, and run `ipfs name ...`? What information am I missing?

**Comment by krl** [comment]
Just run it in a separate terminal

**Comment by RichardLitt** [comment]
Ok. So, if I run that in another terminal, I need to cancel `npm run serve` and rerun it in order to not have init come up every time. 

I don't understand why this needs to be done. Can you write up something about this? I think it should be in the Readme.

**Comment by krl** [comment]
No, init should only appear if your ipns is not pointing to a starlog structure. This should be fixed in this branch.

Could you double check?

If not, could you give the output of

```
ipfs object get  $(ipfs name resolve)
```

**Comment by krl** [comment]
will merge this in the meantime

**Comment by RichardLitt** [comment]
Ran daemon, ran server, init showed up once, then not again. Repointed ipns elsewhere without stopping or starting server, and init showed up twice, and then never again. Not sure why twice. On second time, ran ipfs object get... :

```
10:50 ~/src/starlog $ ipfs object get  $(ipfs name resolve)
{
  "Links": [
    {
      "Name": "log",
      "Hash": "QmQoSGNifuzm9fZ3vUFHHhrpn1fKxcKxonRit9vXVN7iJN",
      "Size": 432231
    }
  ],
  "Data": "{\"type\":\"starlog-feed\",\"feed\":\"QmXBgD6XuHDp2N5XMPcrnXxLtZgVz3rg2YitPEdY6DzZtw\",\"name\":\"
```

Which make sense. Confusing.

**Pull request merged**
