### PR TITLE
Latest stand

### PR DESCRIPTION
**Pull request by krl**
This is the latest stand of the frontend

### CODE REVIEW

**Comment by RichardLitt** [comment]
Cool. Ought I to pull down this PR and work on this branch? Or are you just looking for a code review?

**Comment by krl** [comment]
@RichardLitt hello, i have cleaned up the interfaces now, should make the code more readable. I'd like to have some review and merging of this version.

What i think we might need, is a more straightforward, react-style binding between the search command and the #! path history, so that you can search and then hit back without confusion.

Most things should work in this version.

Could you give it a spin and see if you find any obvious improvements? I'll get to documenting more about the underlying datastructure, but i think it should be pretty straightforward from the usage examples here.

**Comment by krl** [comment]
We also need to make sure that it runs properly in Firefox/non-chrome browsers

**Comment by RichardLitt** [comment]
@krl Added my feedback in #7. To be honest, I have no idea what is going on, and the functionality is limited to me pressing 'Preview' and 'Post' - nothing else works for me, and Post merely removes any text I had written. 

Can you write up what Starlog is supposed to do? That might help me figure out what things are broken - right now, it seems like all of them. Since that's the case, I'm not sure that code review would help too much at the moment.

**Comment by krl** [comment]
Ok, i'm just writing the readme dev docs, and realized how much i presupposed. Writing it all down now!

**Comment by RichardLitt** [comment]
Thanks!

**Pull request merged**
